export const FETCH_GIST_LIST_START = "FETCH_GIST_LIST_START";
export const FETCH_GIST_LIST_SUCCESS = "FETCH_GIST_LIST_SUCCESS";
export const FETCH_GIST_LIST_FAILURE = "FETCH_GIST_LIST_FAILURE";
export const FETCH_GIST_FORK_SUCCESS = "FETCH_GIST_FORK_SUCCESS";
export const FETCH_GIST_FORK_FAILURE = "FETCH_GIST_FORK_FAILURE";
